<<<<<<< HEAD
permalink: /:title.html
title: -----------al
description: "Al3xandr3's Blog"
keywords: programming, data, machine learning, alexandre martins, al3xandr3
production_url: http://al3xandr3.github.io
pygments: false
=======
# Welcome to Jekyll!
#
<<<<<<< HEAD
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yvonne Ng

email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
>>>>>>> origin/gh-pages
markdown: kramdown
author :
  name : Alexandre Matos Martins
  github : al3xandr3
  twitter : al3xandr3
  email: al3xandr3@gmail.com
  linkedin: al3xandr3
disqus_shortname: al3xandr3
analytics: UA-39542235-1
